# Generated by Django 3.2.9 on 2022-01-13 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicCatparking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dmslong', models.DecimalField(db_column='dmsLong', decimal_places=16, max_digits=18)),
                ('dmslat', models.DecimalField(db_column='dmsLat', decimal_places=16, max_digits=18)),
                ('type', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('categoryparking', models.CharField(db_column='categoryParking', max_length=10)),
                ('allowedvehicletype', models.CharField(db_column='allowedVehicleType', max_length=20)),
                ('totalspotnumber', models.IntegerField(db_column='totalSpotNumber')),
                ('timemodified', models.DateTimeField(auto_now=True, db_column='timeModified')),
                ('address', models.CharField(max_length=100)),
                ('requiredpermit', models.CharField(db_column='requiredPermit', max_length=50)),
            ],
            options={
                'db_table': 'public.catParking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PublicOrganization',
            fields=[
                ('orgid', models.AutoField(db_column='orgId', primary_key=True, serialize=False)),
                ('orgname', models.CharField(db_column='orgName', max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('building', models.BooleanField()),
                ('buildlat', models.DecimalField(blank=True, db_column='buildLat', decimal_places=16, max_digits=18, null=True)),
                ('buildlong', models.DecimalField(blank=True, db_column='buildLong', decimal_places=16, max_digits=18, null=True)),
                ('ramp', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'public.organization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PublicParkingspot',
            fields=[
                ('spotid', models.AutoField(db_column='spotId', primary_key=True, serialize=False)),
                ('spotlong', models.DecimalField(db_column='spotLong', decimal_places=0, max_digits=10)),
                ('spotlat', models.DecimalField(db_column='spotLat', decimal_places=0, max_digits=10)),
                ('type', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('categoryspot', models.CharField(db_column='categorySpot', max_length=20)),
            ],
            options={
                'db_table': 'public.parkingSpot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PublicUser',
            fields=[
                ('userid', models.AutoField(db_column='userId', primary_key=True, serialize=False)),
                ('useremail', models.CharField(db_column='userEmail', max_length=50)),
                ('userpassword', models.CharField(db_column='userPassword', max_length=50)),
                ('usercardcode', models.CharField(db_column='userCardCode', max_length=50)),
                ('usercardimage', models.BinaryField(db_column='userCardImage')),
            ],
            options={
                'db_table': 'public.user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PublicSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dmslong', models.DecimalField(db_column='dmsLong', decimal_places=16, max_digits=18)),
                ('dmslat', models.DecimalField(db_column='dmsLat', decimal_places=16, max_digits=18)),
                ('type', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('categoryparking', models.CharField(db_column='categoryParking', max_length=10)),
                ('allowedvehicletype', models.CharField(db_column='allowedVehicleType', max_length=20)),
                ('totalspotnumber', models.IntegerField(db_column='totalSpotNumber')),
                ('timemodified', models.DateTimeField(auto_now=True, db_column='timeModified')),
                ('address', models.CharField(max_length=100)),
                ('requiredpermit', models.CharField(db_column='requiredPermit', max_length=50)),
                ('orgid', models.ForeignKey(db_column='orgId', on_delete=django.db.models.deletion.DO_NOTHING, to='spots.publicorganization')),
            ],
        ),
    ]
