# Generated by Django 3.2.9 on 2022-01-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0002_auto_20220113_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Getdata',
            fields=[
                ('dataid', models.AutoField(db_column='dataId', primary_key=True, serialize=False)),
                ('datatext', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='spotlat',
            field=models.DecimalField(db_column='spotLat', decimal_places=16, max_digits=18),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='spotlong',
            field=models.DecimalField(db_column='spotLong', decimal_places=16, max_digits=18),
        ),
    ]
